# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac91b40fa9654905f6bc9615bb042bd1298c1bf0529e35680c679b1a194ec42c61b7f07c1b4ce84ad302a427c67d2fb75b968ebf4e47ea16e04f60306c8463a4

test:
  secret_key_base: ef05e127fdbcb06ca1e56042760a77f75cedb4d0ea8a72d0f33ef7d95cd2d6895901e149a9fefca6105b4b293525de20add3ec86402c2fdadd3bc4aaab817431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
